import 'package:flutter/material.dart';

// 아이콘 이름을 IconData로 변환하는 함수
IconData getIconData(String? iconName) {
  switch (iconName) {
    // 1. 추천
    case 'category_rounded':
      return Icons.category_rounded;
    case 'school_rounded':
      return Icons.school_rounded;
    case 'work_rounded':
      return Icons.work_rounded;
    case 'fitness_center_rounded':
      return Icons.fitness_center_rounded;
    case 'more_horiz_rounded':
      return Icons.more_horiz_rounded;
    case 'library':
      return Icons.local_library;
    case 'art':
      return Icons.palette;
    case 'computer':
      return Icons.computer;
    case 'edit':
      return Icons.edit;
    case 'keyboard':
      return Icons.keyboard;
    case 'library_books':
      return Icons.library_books;
    case 'language':
      return Icons.language;
    case 'science':
      return Icons.science;

    // 2. 업무와 관련된 아이콘
    case 'business':
      return Icons.business;
    case 'money':
      return Icons.attach_money;
    case 'email':
      return Icons.email;
    case 'meeting':
      return Icons.meeting_room;
    case 'analytics':
      return Icons.analytics;
    case 'assignment':
      return Icons.assignment;
    case 'person_add':
      return Icons.person_add;
    case 'chart':
      return Icons.pie_chart;
    case 'phone':
      return Icons.phone;
    case 'print':
      return Icons.print;
    case 'timeline':
      return Icons.timeline;
    case 'folder_open':
      return Icons.folder_open;
    case 'fact_check':
      return Icons.fact_check;

    // 3. 운동과 관련된 아이콘
    case 'running':
      return Icons.directions_run;
    case 'swimming':
      return Icons.pool;
    case 'soccer':
      return Icons.sports_soccer;
    case 'basketball':
      return Icons.sports_basketball;
    case 'tennis':
      return Icons.sports_tennis;
    case 'volleyball':
      return Icons.sports_volleyball;
    case 'bike':
      return Icons.directions_bike;
    case 'golf':
      return Icons.sports_golf;
    case 'mma':
      return Icons.sports_mma;
    case 'cricket':
      return Icons.sports_cricket;
    case 'esports':
      return Icons.sports_esports;

    // 4. 그외 자기계발과 관련된 아이콘
    case 'ideas':
      return Icons.lightbulb;
    case 'tools':
      return Icons.build;
    case 'healing':
      return Icons.healing;
    case 'spa':
      return Icons.spa;
    case 'park':
      return Icons.park;
    case 'gavel':
      return Icons.gavel;
    case 'hiking':
      return Icons.hiking;
    case 'group_work':
      return Icons.group;
    case 'pets':
      return Icons.pets;
    case 'cleaning':
      return Icons.cleaning_services;
    case 'security':
      return Icons.security;
    case 'volunteer':
      return Icons.volunteer_activism;
    case 'mentoring':
      return Icons.supervised_user_circle;

    // 5. 그 외 일상 관련된 아이콘
    case 'home':
      return Icons.home;
    case 'restaurant':
      return Icons.restaurant;
    case 'coffee':
      return Icons.coffee;
    case 'hospital':
      return Icons.local_hospital;
    case 'shopping':
      return Icons.shopping_cart;
    case 'movie':
      return Icons.movie;
    case 'music':
      return Icons.music_note;
    case 'flight':
      return Icons.flight;
    case 'hotel':
      return Icons.hotel;
    case 'camera':
      return Icons.camera_alt;
    case 'car':
      return Icons.directions_car;
    case 'boat':
      return Icons.directions_boat;
    case 'train':
      return Icons.train;
    case 'subway':
      return Icons.subway;
    case 'walk':
      return Icons.directions_walk;
    case 'cafe':
      return Icons.local_cafe;
    case 'tv':
      return Icons.tv;
    case 'gaming':
      return Icons.videogame_asset;
    case 'theater':
      return Icons.theater_comedy;
    case 'radio':
      return Icons.radio;
    case 'headset':
      return Icons.headset;
    case 'mic':
      return Icons.mic;
    case 'music_video':
      return Icons.music_video;
    case 'bus':
      return Icons.directions_bus;
    case 'painting':
      return Icons.brush;
    case 'map':
      return Icons.map;
    case 'photo':
      return Icons.add_a_photo;
    case 'beach':
      return Icons.beach_access;
    case 'bubble_chart':
      return Icons.bubble_chart;
    case 'wine_bar':
      return Icons.wine_bar;
    case 'weather':
      return Icons.ac_unit;
    case 'kabaddi':
      return Icons.sports_kabaddi;
    case 'village':
      return Icons.holiday_village;
    case 'architecture':
      return Icons.architecture;
    default:
      return Icons.help_outline; // 기본 아이콘
  }
}

String getIconImage(String? iconName) {
  switch (iconName) {
    // 1. 업무와 관련된 아이콘
    case 'business':
      return 'assets/images/emoji/wk_briefcase.png';
    case 'work_rounded':
      return 'assets/images/emoji/wk_office_building.png';
    case 'print':
      return 'assets/images/emoji/wk_fax_machine.png';
    case 'developer':
      return 'assets/images/emoji/wk_developer.png';
    case 'desktop':
      return 'assets/images/emoji/wk_desktop_computer.png';
    case 'teacher':
      return 'assets/images/emoji/wk_teacher.png';
    case 'student':
      return 'assets/images/emoji/wk_student.png';
    case 'artist':
      return 'assets/images/emoji/wk_artist.png';
    case 'email':
      return 'assets/images/emoji/wk_email.png';
    case 'hammer':
      return 'assets/images/emoji/wk_hammer_and_wrench.png';
    case 'laptop':
      return 'assets/images/emoji/wk_laptop.png';
    case 'keyboard':
      return 'assets/images/emoji/wk_keyboard.png';
    case 'bar_chart':
      return 'assets/images/emoji/wk_bar_chart.png';
    case 'line_chart':
      return 'assets/images/emoji/wk_line_chart.png';
    case 'magnifying':
      return 'assets/images/emoji/wk_magnifying_glass.png';
    case 'school':
      return 'assets/images/emoji/wk_school.png';
    case 'cooker':
      return 'assets/images/emoji/wk_cooker.png';
    case 'notepad':
      return 'assets/images/emoji/wk_notepad.png';
    case 'index':
      return 'assets/images/emoji/wk_index.png';
    case 'bank':
      return 'assets/images/emoji/wk_bank.png';
    case 'scientist':
      return 'assets/images/emoji/wk_scientist.png';
    case 'screwdriver':
      return 'assets/images/emoji/wk_screwdriver.png';
    case 'truck':
      return 'assets/images/emoji/wk_truck.png';
    case 'toolbox':
      return 'assets/images/emoji/wk_toolbox.png';
    case 'telephone':
      return 'assets/images/emoji/wk_telephone.png';
    case 'dollar':
      return 'assets/images/emoji/wk_dollar.png';
    case 'classical_building':
      return 'assets/images/emoji/wk_classical_building.png';
    case 'graduation_cap':
      return 'assets/images/emoji/wk_graduation_cap.png';

    // 2. 자기계발과 관련된 아이콘

    case 'palette':
      return 'assets/images/emoji/sd_palette.png';
    case 'walking':
      return 'assets/images/emoji/sd_walking.png';
    case 'soccer':
      return 'assets/images/emoji/sd_soccer.png';
    case 'drum':
      return 'assets/images/emoji/sd_drum.png';
    case 'guitar':
      return 'assets/images/emoji/sd_guitar.png';
    case 'ledger':
      return 'assets/images/emoji/sd_ledger.png';
    case 'mountain':
      return 'assets/images/emoji/sd_mountain.png';
    case 'fitness':
      return 'assets/images/emoji/sd_fitness.png';
    case 'yoga':
      return 'assets/images/emoji/sd_yoga.png';
    case 'running':
      return 'assets/images/emoji/sd_running.png';
    case 'swimming':
      return 'assets/images/emoji/sd-swimming.png';
    case 'biking':
      return 'assets/images/emoji/sd_biking.png';
    case 'snowboarding':
      return 'assets/images/emoji/sd_snowboarding.png';
    case 'globe':
      return 'assets/images/emoji/sd_globe.png';
    case 'meridians':
      return 'assets/images/emoji/sd_globe_with_meridians.png';
    case 'speech':
      return 'assets/images/emoji/sd_speech.png';
    case 'bulb':
      return 'assets/images/emoji/sd_bulb.png';
    case 'books':
      return 'assets/images/emoji/sd_books.png';
    case 'openbook':
      return 'assets/images/emoji/sd_open_book.png';
    case 'pencil':
      return 'assets/images/emoji/sd_pencil.png';
    case 'ruler':
      return 'assets/images/emoji/sd_ruler.png';
    case 'trophy':
      return 'assets/images/emoji/sd_trophy.png';
    case 'writing':
      return 'assets/images/emoji/sd_writing.png';
    case 'basketball':
      return 'assets/images/emoji/sd_basketball.png';

    // 3. 일상생활 관련 아이콘
    case 'baby':
      return 'assets/images/emoji/dl_baby.png';
    case 'baby_bottle':
      return 'assets/images/emoji/dl_baby_bottle.png';
    case 'bath':
      return 'assets/images/emoji/dl_bath.png';
    case 'camera':
      return 'assets/images/emoji/dl_camera.png';
    case 'cat':
      return 'assets/images/emoji/dl_cat.png';
    case 'cat_face':
      return 'assets/images/emoji/dl_cat_face.png';
    case 'clapper':
      return 'assets/images/emoji/dl_clapper.png';
    case 'couch':
      return 'assets/images/emoji/dl_couch.png';
    case 'airplane':
      return 'assets/images/emoji/dl_airplane.png';
    case 'automobile':
      return 'assets/images/emoji/dl_automobile.png';
    case 'badminton':
      return 'assets/images/emoji/dl_badminton.png';
    case 'blossom':
      return 'assets/images/emoji/dl_blossom.png';
    case 'bread':
      return 'assets/images/emoji/dl_bread.png';
    case 'broom':
      return 'assets/images/emoji/dl_broom.png';
    case 'bubbles':
      return 'assets/images/emoji/dl_bubbles.png';
    case 'church':
      return 'assets/images/emoji/dl_church.png';
    case 'beer':
      return 'assets/images/emoji/dl_beer.png';
    case 'wine':
      return 'assets/images/emoji/dl_wine.png';
    case 'golf':
      return 'assets/images/emoji/dl_golf.png';
    case 'plate':
      return 'assets/images/emoji/dl_plate.png';
    case 'luggage':
      return 'assets/images/emoji/dl_luggage.png';
    case 'motorcycle':
      return 'assets/images/emoji/dl_motorcycle.png';
    case 'running_shoe':
      return 'assets/images/emoji/dl_running_shoe.png';
    case 'skateboard':
      return 'assets/images/emoji/dl_skateboard.png';
    case 'game':
      return 'assets/images/emoji/dl_game.png';
    case 'dog':
      return 'assets/images/emoji/dl_dog.png';
    case 'dog_face':
      return 'assets/images/emoji/dl_dog_face.png';
    case 'cards':
      return 'assets/images/emoji/dl_playing_cards.png';
    case 'fox':
      return 'assets/images/emoji/dl_fox.png';
    case 'dice':
      return 'assets/images/emoji/dl_dice.png';
    case 'headphone':
      return 'assets/images/emoji/dl_headphone.png';
    case 'house':
      return 'assets/images/emoji/dl_house.png';
    case 'metro':
      return 'assets/images/emoji/dl_metro.png';
    case 'music':
      return 'assets/images/emoji/dl_music.png';
    case 'popcorn':
      return 'assets/images/emoji/dl_popcorn.png';
    case 'sweat':
      return 'assets/images/emoji/dl_sweat.png';
    case 'tea':
      return 'assets/images/emoji/dl_tea.png';
    case 'television':
      return 'assets/images/emoji/dl_television.png';
    case 'tent':
      return 'assets/images/emoji/dl_tent.png';
    case 'toothbrush':
      return 'assets/images/emoji/dl_toothbrush.png';
    case 'picnic':
      return 'assets/images/emoji/dl_picnic.png';
    case 'mobile':
      return 'assets/images/emoji/dl_mobile.png';
    case 'map':
      return 'assets/images/emoji/dl_map.png';
    case 'wrench':
      return 'assets/images/emoji/dl_wrench.png';
    case 'zzz':
      return 'assets/images/emoji/dl_zzz.png';

    // 4. 도형 관련된 아이콘
    case 'category':
      return 'assets/images/emoji/sh_category.png';
    case 'alien':
      return 'assets/images/emoji/sh_alien.png';
    case 'tree':
      return 'assets/images/emoji/sh_tree.png';
    case 'clapping':
      return 'assets/images/emoji/sh_clapping.png';
    case 'construction':
      return 'assets/images/emoji/sh_construction.png';
    case 'dizzy':
      return 'assets/images/emoji/sh_dizzy.png';
    case 'alarm':
      return 'assets/images/emoji/sh_alarm.png';
    case 'cityscape':
      return 'assets/images/emoji/sh_cityscape.png';
    case 'cityscape_at_dusk':
      return 'assets/images/emoji/dl_cityscape_at_dusk.png';
    case 'seedling':
      return 'assets/images/emoji/sh_seedling.png';
    case 'point_star':
      return 'assets/images/emoji/sh_point_star.png';
    case 'exclamation_question_mark':
      return 'assets/images/emoji/sh_exclamation_question_mark.png';
    case 'eye':
      return 'assets/images/emoji/sh_eye.png';
    case 'eyes':
      return 'assets/images/emoji/sh_eyes.png';
    case 'footprint':
      return 'assets/images/emoji/sh_footprint.png';
    case 'glasses':
      return 'assets/images/emoji/sh_glasses.png';
    case 'gloves':
      return 'assets/images/emoji/sh_gloves.png';
    case 'glowing_star':
      return 'assets/images/emoji/sh_glowing_star.png';
    case 'green_circle':
      return 'assets/images/emoji/sh_green_circle.png';
    case 'green_heart':
      return 'assets/images/emoji/sh_green_heart.png';
    case 'green_square':
      return 'assets/images/emoji/sh_green_square.png';
    case 'grey_heart':
      return 'assets/images/emoji/sh_grey_heart.png';
    case 'growing_heart':
      return 'assets/images/emoji/sh_growing_heart.png';
    case 'heart_exclamation':
      return 'assets/images/emoji/sh_heart_exclamation.png';
    case 'hundred':
      return 'assets/images/emoji/sh_hundred.png';
    case 'infinity':
      return 'assets/images/emoji/sh_infinity.png';
    case 'key':
      return 'assets/images/emoji/sh_key.png';
    case 'keycap':
      return 'assets/images/emoji/sh_keycap.png';
    case 'blue_heart':
      return 'assets/images/emoji/sh_blue_heart.png';
    case 'locked':
      return 'assets/images/emoji/sh_locked.png';
    case 'speaker':
      return 'assets/images/emoji/sh_speaker.png';
    case '1st_medal':
      return 'assets/images/emoji/sh_1st_medal.png';
    case '2nd_medal':
      return 'assets/images/emoji/sh_2nd_medal.png';
    case '3rd_medal':
      return 'assets/images/emoji/sh_3rd_medal.png';
    case 'money_wing':
      return 'assets/images/emoji/sh_money_wing.png';
    case 'city_night':
      return 'assets/images/emoji/sh_city_night.png';
    case 'no_mobile':
      return 'assets/images/emoji/sh_no_mobile.png';
    case 'party':
      return 'assets/images/emoji/sh_party.png';
    case 'plus':
      return 'assets/images/emoji/sh_plus.png';
    case 'pinned':
      return 'assets/images/emoji/sh_pinned.png';
    case 'rainbow':
      return 'assets/images/emoji/sh_rainbow.png';
    case 'robot':
      return 'assets/images/emoji/sh_robot.png';
    case 'bullseye':
      return 'assets/images/emoji/sh_bullseye.png';
    case 'scroll':
      return 'assets/images/emoji/sh_scroll.png';
    case 'compass':
      return 'assets/images/emoji/sh_compass.png';
    case 'crown':
      return 'assets/images/emoji/sh_crown.png';
    case 'fire':
      return 'assets/images/emoji/sh_fire.png';
    case 'gear':
      return 'assets/images/emoji/sh_gear.png';
    case 'ghost':
      return 'assets/images/emoji/sh_ghost.png';
    case 'high_voltage':
      return 'assets/images/emoji/sh_high_voltage.png';
    case 'hourglass_done':
      return 'assets/images/emoji/sh_hourglass_done.png';
    case 'hourglass_not_done':
      return 'assets/images/emoji/sh_hourglass_not_done.png';
    case 'label':
      return 'assets/images/emoji/sh_label.png';
    case 'magic_wand':
      return 'assets/images/emoji/sh_magic_wand.png';
    case 'police_car_light':
      return 'assets/images/emoji/sh_police_car_light.png';
    case 'rocket':
      return 'assets/images/emoji/sh_rocket.png';
    case 'sign_of_the_horns_light':
      return 'assets/images/emoji/sh_sign_of_the_horns_light.png';
    case 'sparkles':
      return 'assets/images/emoji/sh_sparkles.png';
    case 'star':
      return 'assets/images/emoji/sh_star.png';
    case 'stopwatch':
      return 'assets/images/emoji/sh_stopwatch.png';
    case 'calendar':
      return 'assets/images/emoji/sh_calendar.png';
    case 'clock':
      return 'assets/images/emoji/sh_clock.png';
    case 'shopping':
      return 'assets/images/emoji/sh_shopping.png';

    case 'shuffle':
      return 'assets/images/emoji/sh_shuffle.png';
    case 'snowman':
      return 'assets/images/emoji/sh_snowman.png';
    case 'monkey':
      return 'assets/images/emoji/sh_monkey.png';
    case 'sun':
      return 'assets/images/emoji/sh_sun.png';
    case 'sunrise':
      return 'assets/images/emoji/sh_sunrise.png';
    case 'sunset':
      return 'assets/images/emoji/sh_sunset.png';
    case 'thumbs_down':
      return 'assets/images/emoji/sh_thumbs_down.png';
    case 'thumbs_up':
      return 'assets/images/emoji/sh_thumbs_up.png';
    case 'ticket':
      return 'assets/images/emoji/sh_ticket.png';
    case 'trex':
      return 'assets/images/emoji/sh_trex.png';
    case 'two_heart':
      return 'assets/images/emoji/sh_two_heart.png';
    case 'unicorn':
      return 'assets/images/emoji/sh_unicorn.png';
    case 'unlocked':
      return 'assets/images/emoji/sh_unlocked.png';
    case 'up_button':
      return 'assets/images/emoji/sh_up_button.png';
    case 'victory':
      return 'assets/images/emoji/sh_victory.png';
    case 'bookmark':
      return 'assets/images/emoji/sh_bookmark.png';
    case 'yellow_heart':
      return 'assets/images/emoji/sh_yellow_heart.png';

    // 기본 아이콘
    default:
      return 'assets/images/emoji/sh_ghost.png'; // 기본 아이콘
  }
}
